{% set name = "injector" %}
{% set version = "0.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/injector-{{ version }}.tar.gz
  sha256: 0c82dedc8e1354e8fd22ab3d99b88bddef6dedb9c77d6c22c4d89db3d15837f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pypandoc
    - python >=3.6
  run:
    - python >=3.6
    - typing_extensions >=3.7.4

test:
  imports:
    - injector
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alecthomas/injector
  summary: Injector - Python dependency injection framework, inspired by Guice
  license: BSD-3-Clause
  # License file manually packaged: See: https://github.com/alecthomas/injector/pull/160
  license_file: COPYING

extra:
  recipe-maintainers:
    - fuglede
